# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clueless', '0004_auto_20161207_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gameResult',
            field=models.IntegerField(choices=[(-1, 'Lost'), (0, 'Neither'), (1, 'Won')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='lastUpdateTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 9, 2, 6, 41, 226386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='startTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 12, 9, 2, 6, 41, 226359, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Started'), (2, 'Complete')], default=0),
        ),
    ]
